[build]
  base = "Frontend"
  publish = "dist"
  command = "npm install --no-optional && npm run build"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_FLAGS = "--no-optional --no-audit --no-fund"
  ROLLUP_SKIP_NODEJS_RESOLUTION = "true"
  SKIP_INSTALL_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200