[build]
  base = "Frontend"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --no-audit --no-fund"
  ROLLUP_SKIP_NODEJS_RESOLUTION = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200